apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app
  namespace: weather-app
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-app
  source:
    repoURL: https://github.com/traceherrell/energy-deploy.git
    targetRevision: main
    path:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
