apiVersion: v1
kind: Secret
metadata:
  name: azure-devops-creds
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository # <-- This label is key
stringData:
  type: git
  url: <your-azure-repo-url> # <-- This URL must match application.yaml
  username: <your-username>
  password: <your-pat>
