apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-api-app
  namespace: energy-api-app
  labels:
    app: energy-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-api-app
  template:
    metadata:
      labels:
        app: energy-api-app
    spec:
      containers:
        - name: energy-api-app
          image: sha256:706c46ef195e6c1b7e65b9900f83c00446f310c92b839f35b1afd81d295e25b2
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
